# -*- coding: utf-8 -*-
"""travel-assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3yVUGsWc9gylvPfHcFcaAF1-BOe4doD
"""

!pip install langchain langchain-community langchain-google-genai requests duckduckgo-search python-dotenv

import os
import requests
from typing import Optional, Type
from langchain.tools import BaseTool, tool
from langchain.agents import create_tool_calling_agent, AgentExecutor
from langchain.prompts import ChatPromptTemplate
from langchain_community.tools import DuckDuckGoSearchRun
from langchain_google_genai import ChatGoogleGenerativeAI  # For Gemini
from dotenv import load_dotenv
import json
from google.colab import userdata

# Import userdata for Colab secrets
from google.colab import userdata

# Get API keys from Colab secrets
GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
WEATHER_API_KEY = userdata.get('WEATHER_API_KEY')  # Your WeatherAPI key

# Verify Google API key is available
if GOOGLE_API_KEY:
    print("✅ Google API key found in Colab secrets!")
else:
    print("❌ Google API key not found. Please set GOOGLE_API_KEY in Colab secrets.")
    print("Go to Colab secrets tab (🔑) and add your Google API key.")

# Verify Weather API key
if WEATHER_API_KEY:
    print("✅ Weather API key configured!")
else:
    print("❌ Weather API key not found.")

print("✅ API keys configured successfully!")
print(f"Google API Key available: {'Yes' if GOOGLE_API_KEY else 'No'}")
print(f"Weather API Key available: {'Yes' if WEATHER_API_KEY else 'No'}")

# Initialize Google Gemini 1.5 Flash (Free version)
llm = ChatGoogleGenerativeAI(
    model="gemini-1.5-flash",  # Free model with generous limits
    temperature=0.1,           # Low temperature for consistent responses
    google_api_key=GOOGLE_API_KEY,
    convert_system_message_to_human=True  # Important for Gemini compatibility
)

print("✅ Google Gemini 1.5 Flash (Free) initialized successfully!")
print(f"Using model: Gemini 1.5 Flash")

# Test the LLM connection
try:
    test_response = llm.invoke("Hello, are you working?")
    print(f"✅ LLM test successful: {test_response.content[:50]}...")
except Exception as e:
    print(f"❌ LLM test failed: {str(e)}")
    print("💡 Tip: Make sure your Google API key is valid and has Gemini API access enabled")

@tool
def get_weather_forecast(city: str) -> str:
    """
    Fetch current weather and forecast for a given city using WeatherAPI.

    Args:
        city (str): The name of the city to get weather for

    Returns:
        str: Weather information including current conditions and forecast
    """
    try:
        # WeatherAPI endpoint for current weather and forecast
        url = f"http://api.weatherapi.com/v1/forecast.json"
        params = {
            'key': WEATHER_API_KEY,
            'q': city,
            'days': 3,  # 3-day forecast
            'aqi': 'no',  # Air quality index not needed
            'alerts': 'no'  # Weather alerts not needed
        }

        response = requests.get(url, params=params)
        response.raise_for_status()  # Raise an exception for bad status codes

        data = response.json()

        # Extract relevant weather information
        current = data['current']
        location = data['location']
        forecast = data['forecast']['forecastday']

        # Format the weather information
        weather_info = f"""
🌍 Weather for {location['name']}, {location['country']}:

📍 Current Conditions:
- Temperature: {current['temp_c']}°C ({current['temp_f']}°F)
- Condition: {current['condition']['text']}
- Feels like: {current['feelslike_c']}°C ({current['feelslike_f']}°F)
- Humidity: {current['humidity']}%
- Wind: {current['wind_kph']} km/h {current['wind_dir']}

📅 3-Day Forecast:
"""

        for day in forecast:
            date = day['date']
            day_info = day['day']
            weather_info += f"""
- {date}: {day_info['condition']['text']}
  High: {day_info['maxtemp_c']}°C, Low: {day_info['mintemp_c']}°C
  Rain chance: {day_info['daily_chance_of_rain']}%
"""

        return weather_info

    except requests.exceptions.RequestException as e:
        return f"❌ Error fetching weather data: {str(e)}"
    except KeyError as e:
        return f"❌ Error parsing weather data: Missing key {str(e)}"
    except Exception as e:
        return f"❌ Unexpected error: {str(e)}"

# Test the weather tool
print("✅ Weather tool created successfully!")
print("Testing weather tool...")
test_weather = get_weather_forecast("London")
print(test_weather[:200] + "..." if len(test_weather) > 200 else test_weather)

# Initialize DuckDuckGo search tool (completely free, no API key required)
search_tool = DuckDuckGoSearchRun()

@tool
def get_tourist_attractions(city: str) -> str:
    """
    Search for top tourist attractions and interesting places to visit in a given city.

    Args:
        city (str): The name of the city to search attractions for

    Returns:
        str: Information about top tourist attractions in the city
    """
    try:
        # Create a focused search query for tourist attractions
        search_query = f"top tourist attractions {city} places to visit travel guide"

        # Perform the search
        search_results = search_tool.run(search_query)

        # Format the results for better readability
        formatted_results = f"""
🏛️ Top Tourist Attractions in {city}:

{search_results}

💡 Tips for visiting {city}:
- Check opening hours and ticket prices in advance
- Consider purchasing city passes for multiple attractions
- Use public transportation or walking when possible
- Try local cuisine and visit local markets
"""

        return formatted_results

    except Exception as e:
        return f"❌ Error searching for attractions: {str(e)}"

# Test the attractions tool
print("✅ Tourist attractions tool created successfully!")
print("Testing attractions tool...")
test_attractions = get_tourist_attractions("Paris")
print(test_attractions[:300] + "..." if len(test_attractions) > 300 else test_attractions)

# Create a list of tools available to the agent
tools = [get_weather_forecast, get_tourist_attractions]

# Create a prompt template for the travel assistant
prompt = ChatPromptTemplate.from_messages([
    ("system", """You are an intelligent Travel Assistant AI. Your role is to help users plan their trips by providing:

1. 🌤️ **Weather Information**: Current conditions and forecast for their destination
2. 🏛️ **Tourist Attractions**: Top places to visit and local recommendations

**Instructions:**
- Always be helpful, informative, and enthusiastic about travel
- Use the weather tool to get current weather and forecast
- Use the attractions tool to find interesting places to visit
- Provide practical travel advice when relevant
- Format your responses clearly with emojis and sections
- If a user asks about multiple cities, handle each one separately
- Always be encouraging and positive about travel experiences

**Available Tools:**
- get_weather_forecast: Get weather information for any city
- get_tourist_attractions: Find top tourist attractions in any city"""),

    ("user", "{input}"),
    ("placeholder", "{agent_scratchpad}"),
])

# Create the tool-calling agent
agent = create_tool_calling_agent(llm, tools, prompt)

# Create an agent executor
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,  # Set to False to reduce output
    handle_parsing_errors=True,
    max_iterations=5  # Limit iterations to prevent infinite loops
)

print("✅ Travel Assistant Agent created successfully!")
print("🤖 Agent is ready to help with travel planning!")

def interactive_travel_assistant():
    """
    Interactive interface for the travel assistant
    """
    print("🌍 Welcome to your Intelligent Travel Assistant! 🌍")
    print("I can help you with weather information and tourist attractions for any destination.")
    print("Type 'quit' or 'exit' to end the conversation.\n")

    while True:
        try:
            # Get user input
            user_input = input("🏖️ Enter a destination you'd like to explore (or 'quit' to exit): ").strip()

            # Check if user wants to quit
            if user_input.lower() in ['quit', 'exit', 'q']:
                print("✈️ Happy travels! Thanks for using the Travel Assistant!")
                break

            if not user_input:
                print("Please enter a valid destination name.")
                continue

            print(f"\n🔍 Gathering travel information for {user_input}...")
            print("=" * 60)

            # Get travel information
            result = travel_assistant(user_input)
            print(result)
            print("\n" + "=" * 60 + "\n")

        except KeyboardInterrupt:
            print("\n✈️ Happy travels! Thanks for using the Travel Assistant!")
            break
        except Exception as e:
            print(f"❌ An error occurred: {str(e)}")
            print("Please try again with a different destination.\n")

# Run the interactive assistant
interactive_travel_assistant()